<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c8aca233-6597-451a-a8cf-583cfcd36bea</testSuiteGuid>
   <testCaseLink>
      <guid>99976aef-52b5-4c1f-bc2f-a8b319ca4dea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>072a5f17-21f9-41d9-a883-5dc914c76db6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>072a5f17-21f9-41d9-a883-5dc914c76db6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>de32caf3-7eac-4066-8bce-304ec8345f36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>072a5f17-21f9-41d9-a883-5dc914c76db6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>a05943c7-d515-4c22-b482-1142d90e4000</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>072a5f17-21f9-41d9-a883-5dc914c76db6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>848ba022-4421-4f87-b75f-71916a25158f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
