<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>area</name>
   <tag></tag>
   <elementGuidId>3d5abb06-ca01-4ae5-8c23-8dec41875f74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainImageContent']/map/area</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>area[alt=&quot;Birds&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Birds&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>area</value>
      <webElementGuid>f7a86425-d8c2-404a-a4f2-667bf6fc6a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Birds</value>
      <webElementGuid>433ac903-9163-4c38-b875-90211fa513d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>coords</name>
      <type>Main</type>
      <value>72,2,280,250</value>
      <webElementGuid>06297e62-9b79-4ef5-8ef4-c6235386e20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Catalog.action?viewCategory=&amp;categoryId=BIRDS</value>
      <webElementGuid>e685d0bd-50b7-4249-a83b-15925d6a080e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>RECT</value>
      <webElementGuid>100ef112-2c39-40e4-9e06-d7bd74d86a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainImageContent&quot;)/map[1]/area[1]</value>
      <webElementGuid>44f37c58-b4c3-4c38-b2c1-7a1b272d81e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainImageContent']/map/area</value>
      <webElementGuid>797c756d-2cd3-45d4-94de-e598be7308b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//area</value>
      <webElementGuid>e162490e-c3a2-4db8-82ea-acd184b87f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//area[@alt = 'Birds' and @href = 'Catalog.action?viewCategory=&amp;categoryId=BIRDS']</value>
      <webElementGuid>a8b9b6b1-c75f-4359-a7ec-8654baa8d8c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
